# Connexion au MySQL de XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/psg_archive?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# Affichage des logs SQL (très utile pour débugger)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
